apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-blogconfig
data:
  TITLE: "{{ .Values.blog.title }} v3"
  COLOR: {{ .Values.blog.color }}
  BODY: {{ .Values.blog.body }}
